-- 코드를 입력하세요
SELECT R2.FOOD_TYPE, R2.REST_ID, R2.REST_NAME, R2.FAVORITES
FROM (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
      ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANK
      FROM REST_INFO
      ORDER BY FAVORITES DESC) R2
WHERE RANK = 1
ORDER BY FOOD_TYPE DESC;
