-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE UPPER(a.SEX_UPON_INTAKE) LIKE '%INTACT%' AND UPPER(b.SEX_UPON_OUTCOME) LIKE '%NEUTERED%'
OR UPPER(a.SEX_UPON_INTAKE) LIKE '%INTACT%' AND UPPER(b.SEX_UPON_OUTCOME) LIKE '%SPAYED%'
ORDER BY ANIMAL_ID;