-- 코드를 작성해주세요
WITH CTE AS (
SELECT 
CASE
    WHEN MONTH(DIFFERENTIATION_DATE) IN (1, 2, 3) THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) IN (4, 5, 6) THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) IN (7, 8, 9) THEN '3Q'
    WHEN MONTH(DIFFERENTIATION_DATE) IN (10, 11, 12) THEN '4Q'
END AS QUARTER
FROM ECOLI_DATA )
SELECT QUARTER, COUNT(QUARTER) AS ECOLI_COUNT
FROM CTE
GROUP BY 1
ORDER BY QUARTER ASC;