-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, X.TOTAL_SALES AS TOTAL_SALES
FROM (SELECT WRITER_ID AS USER_ID, 
             SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000) X, 
             USED_GOODS_USER B
WHERE B.USER_ID = X.USER_ID
ORDER BY TOTAL_SALES ASC;