-- 코드를 입력하세요
SELECT HOUR, COUNT(*) AS COUNT
FROM (SELECT TO_NUMBER(TO_CHAR(CAST(DATETIME AS DATE), 'HH24')) AS HOUR
      FROM ANIMAL_OUTS
      WHERE (TO_NUMBER(TO_CHAR(CAST(DATETIME AS DATE), 'HH24')) >= 9)
      AND (TO_NUMBER(TO_CHAR(CAST(DATETIME AS DATE), 'HH24')) <= 19)
      )
GROUP BY HOUR
ORDER BY HOUR ASC;