-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (SELECT 1
              FROM SKILLCODES S
              WHERE (S.CODE & D.SKILL_CODE != 0)
              AND ((S.NAME = 'Python') OR (S.NAME = 'C#')))
ORDER BY D.ID ASC;