-- 코드를 작성해주세요
WITH CTE AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY 1
)
SELECT C.YEAR, (C.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
LEFT JOIN CTE C ON YEAR(E.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY 1 ASC, 2 ASC;