-- 코드를 입력하세요
SELECT DISTINCT B.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE LIKE '%세단%'
AND TO_CHAR(B.START_DATE, 'YYYY-MM') = '2022-10'
ORDER BY B.CAR_ID DESC;