-- 코드를 작성해주세요
WITH CTE AS 
(   SELECT A.FISH_TYPE, B.FISH_NAME, MAX(A.LENGTH) AS LENGTH
    FROM FISH_INFO A
    JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY A.FISH_TYPE, B.FISH_NAME
)
SELECT A.ID, C.FISH_NAME, C.LENGTH
FROM CTE C
JOIN FISH_INFO A ON A.LENGTH = C.LENGTH 
AND A.FISH_TYPE = C.FISH_TYPE