-- 코드를 작성해주세요
WITH CTE AS(
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT C.SCORE, C.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL 
FROM CTE C
JOIN HR_EMPLOYEES B ON C.EMP_NO = B.EMP_NO 
ORDER BY C.SCORE DESC
LIMIT 1