-- 코드를 입력하세요
WITH CTE AS (
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY PRICE DESC
)
SELECT CATEGORY, MAX(MAX_PRICE), PRODUCT_NAME
FROM CTE
GROUP BY CATEGORY