-- 코드를 작성해주세요
WITH CTE AS (
    SELECT FISH_TYPE, COALESCE(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM CTE
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY 3 ASC;

